### PR TITLE
update custom layer to be compatible with version 3.11 of the JSAPI

### PR DESCRIPTION
**Pull request by jgravois**
finally figured out how to upgrade to version 3.11

working sample here
http://jgravois.github.io/esri-d3/mlb.html

### CODE REVIEW

**Comment by jgravois** [comment]
@chelm give me push access to this repo and i'll never let it :sunset:

**Comment by chelm** [comment]
@jgravois will do!

**Comment by jgravois** [comment]
ha. the 3.15 update should be a cinch.

**Comment by chelm** [comment]
the deed is done, @jgravois

**Pull request merged**
